version: "3.5"

services:
    versus_next-nginx:
        container_name: versus_next-nginx
        build:
            context: ./docker/nginx
            args:
                UID: $U_ID
                NGINX_FASTCGI_READ_TIMEOUT: 300 # require BUILD si se modifica: establecer valores altos para poder depurar
        volumes:
            - ./:/appdata/www
        depends_on:
            - versus_next-php
        networks:
            atlas-network:
              aliases:
                    - dev.next.vsgamers.es


    versus_next-php:
        container_name: versus_next-php
        build:
            context: docker/php
            args:
                UID: $U_ID
        environment:
            XDEBUG_CLIENT_HOST: $HOST_IP
            XDEBUG_CLIENT_PORT: 9003
        volumes:
            - ./:/appdata/www
            - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
        depends_on:
            - versus_next-db
        networks:
            - atlas-network
    versus_next-db:
        container_name: versus_next-db
        image: mysql:8.0.26
        ports:
            - 10003:3306
        environment:
            MYSQL_DATABASE: versus_next
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - versus_next-db-data:/var/lib/mysql
        networks:
            - atlas-network
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION']

volumes:
    versus_next-db-data:

networks:
    atlas-network:
        external: true
