VS\Next\Promotions\Domain\Profit\Profit:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: type
    type: string
    length: 20
  discriminatorMap:
    product_amount: VS\Next\Promotions\Domain\Profit\Types\ProductAmountProfit
    product_percent: VS\Next\Promotions\Domain\Profit\Types\ProductPercentProfit
    cart_amount: VS\Next\Promotions\Domain\Profit\Types\CartAmountDiscountProfit
    cart_percent: VS\Next\Promotions\Domain\Profit\Types\CartPercentDiscountProfit
    cheapest_product: VS\Next\Promotions\Domain\Profit\Types\CheapestProductPercentDiscountProfit    
    free_product_buying_product: VS\Next\Promotions\Domain\Profit\Types\FreeProductBuyingProductProfit    
  table: promotions_judgments_profits
  id:
    id:
      type: profit_id
      unique: true
      id: true    
  oneToOne:
    judgment:
      targetEntity: VS\Next\Promotions\Domain\Judgment\Judgment
      mappedBy: profit     


  