# controllers:
#     resource: ../src/Controller/
#     type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

vs_next_checkout:
    resource:       "@VSNextCheckoutBundle/config/routing.yml"
    prefix:         /checkout
    name_prefix:    vs_next_checkout
    trailing_slash_on_root: false

