VS\Next\Catalog\Domain\Brand\Brand:
  type: entity
  table: brands    
  id:
    id:
      type: uuid
      unique: true
      id: true
  embedded:
    name:
      class: VS\Next\Catalog\Domain\Brand\BrandName      
      columnPrefix: false