VS\Next\Catalog\Domain\Category\Category:
  type: entity
  table: categories  
  id:
    id:
      type: category_id
      unique: true
      id: true
  embedded:
    name:
      class: VS\Next\Catalog\Domain\Category\CategoryName      
      columnPrefix: false