VS\Next\Catalog\Domain\Product\Entity\Product:
  type: entity
  inheritanceType: SINGLE_TABLE
  discriminatorColumn:
    name: type
    type: string
    length: 10
  discriminatorMap:
    normal: VS\Next\Catalog\Domain\Product\NormalProduct
    gift_card: VS\Next\Catalog\Domain\Product\GiftCardProduct
    redeemable: VS\Next\Catalog\Domain\Product\RedeemableProduct
    variable: VS\Next\Catalog\Domain\Product\VariableProduct
    variation: VS\Next\Catalog\Domain\Product\VariationProduct
  table: products  
  repositoryClass: VS\Next\Catalog\Infrastructure\Repository\ProductDoctrineRepository
  id:
    id:
      type: product_id
      unique: true
      id: true
  fields:
    allowDirectSales:
      type: boolean    
  embedded:
    name:
      class: VS\Next\Catalog\Domain\Product\Entity\ProductName      
      columnPrefix: false
    sku:
      class: VS\Next\Catalog\Domain\Product\Entity\ProductSku
      columnPrefix: false
    status:
      class: VS\Next\Catalog\Domain\Product\Entity\ProductStatus
      columnPrefix: false    
  manyToOne:
    category:
      targetEntity: VS\Next\Catalog\Domain\Category\Category

